ateam-dev/web-speed-hackathon-2021-leaderboard

.github/workflows/deploy.yml, scripts/leaderboard/wrangler.toml
デバッグ用にPRでのアクション起動を許可してみたところ無事に通過し、デプロイで来たことを確認済み
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/actions/runs/2100149291
=> Setup github actions for deploy

scripts/leaderboard/app/components/MeasurementReuestForm.tsx, scripts/leaderboard/app/routes/index.tsx
=> Add create measurement request endpoint

.github/workflows/deploy.yml, scripts/leaderboard/.env.sample, scripts/leaderboard/app/components/Navbar.tsx, scripts/leaderboard/app/libs/auth.server.ts, scripts/leaderboard/app/libs/supabase.server.ts, scripts/leaderboard/app/root.tsx, scripts/leaderboard/app/routes/auth/callback.tsx, scripts/leaderboard/app/routes/auth/login.tsx, scripts/leaderboard/app/routes/auth/logout.tsx, scripts/leaderboard/app/routes/dashboard/index.tsx, scripts/leaderboard/app/routes/index.tsx, scripts/leaderboard/global.d.ts, scripts/leaderboard/package.json, yarn.lock
- GoogleAuthを使用したログインページ・ログアウト処理
- 未ログイン時のリダイレクト処理
- ナビゲートバーに、自身のアカウント情報を表示
下記別MRで対応
- Userモデルとの接続
- Teamの作成・所属
=> Create Login page and logout feature

scripts/leaderboard/app/components/MeasurementReuestForm.tsx, scripts/leaderboard/app/graphql/mutations/queue.graphql, scripts/leaderboard/app/graphql/request/Queue.ts, scripts/leaderboard/app/routes/dashboard/index.tsx, scripts/leaderboard/generated/graphql.tsx, scripts/leaderboard/generated/modules.d.ts
=> Add line up for measurement

scripts/leaderboard/app/components/MeasurementReuestForm.tsx, scripts/leaderboard/app/components/TeamCard.tsx, scripts/leaderboard/app/components/atoms/Button.tsx, scripts/leaderboard/app/graphql/mutations/queue.graphql, scripts/leaderboard/app/graphql/mutations/team.graphql, scripts/leaderboard/app/graphql/request/Teaming.ts, scripts/leaderboard/app/graphql/schema/schema.graphql, scripts/leaderboard/app/routes/auth/login.tsx, scripts/leaderboard/app/routes/dashboard/__layout/index.tsx, scripts/leaderboard/app/routes/dashboard/__layout/teams.tsx, scripts/leaderboard/generated/graphql.schema.json, scripts/leaderboard/generated/graphql.tsx, scripts/leaderboard/prisma/migrations/20220408050853_/migration.sql, scripts/leaderboard/prisma/schema.prisma
チームに参加する機能
https://user-images.githubusercontent.com/6711766/162377499-c9b985f6-df21-481e-aa47-a86a493f2c1e.mov
- graphqlの問題はidカラムをIntからUUIDにしても解決はしなかった
- 該当の処理はsupabase-jsを使用して回避する
- マイグレーション自体は一旦元には戻さずにこのままで行こうと思う。
=> Create a feature of joining team

scripts/leaderboard/package.json, scripts/leaderboard/prisma/seed.ts, yarn.lock
=> Create db seeds

.dockerignore, docker-compose.yml, scripts/measure/Dockerfile, scripts/measure/config/default.yml, scripts/measure/docker-entrypoint.sh, scripts/measure/package.json, scripts/measure/src/index.ts, scripts/scoring/src/index.ts, scripts/vrt/src/capture_screenshot.ts, scripts/vrt/src/index.ts, yarn.lock
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/issues/22
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/issues/25
- 計測実行用のAPIエンドポイント追加
- VRTの実行および実行結果処理追加
- スコア計測の実行処理追加
- 開発用のコンテナ設定を同時に追加
=> Add measure server

scripts/leaderboard/app/components/MeasurementReuestForm.tsx, scripts/leaderboard/app/components/TeamCard.tsx, scripts/leaderboard/app/graphql/request/Queue.ts, scripts/leaderboard/app/graphql/request/Sample.ts, scripts/leaderboard/app/graphql/request/Teaming.ts, scripts/leaderboard/app/routes/dashboard/__layout/index.tsx, scripts/leaderboard/app/routes/dashboard/__layout/teams.tsx
supabaseのpg_graphqlエンドポイントが404になっているため、supabase-jsのclientに一時的に置き換え。
=> Replace apollo-client by supabase-client for pg_graqhql endopoint is 404

scripts/measure/package.json, scripts/measure/src/database.ts, scripts/measure/src/index.ts
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/issues/23
=> Add update queue status function

scripts/measure/src/database.ts, scripts/measure/src/index.ts
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/issues/24
=> Add create Measurement function

scripts/leaderboard/app/components/Chart.tsx, scripts/leaderboard/app/components/MeasurementReuestForm.tsx, scripts/leaderboard/app/graphql/request/Measurement.ts, scripts/leaderboard/app/graphql/request/Teaming.ts, scripts/leaderboard/app/routes/dashboard/__layout/index.tsx, scripts/leaderboard/package.json, scripts/leaderboard/prisma/migrations/20220411070000_/migration.sql, scripts/leaderboard/prisma/seed.ts, yarn.lock
- supabase側にviewを作って、1値時間ごとのデータを丸めて返すように
- 該当時間の中での最大値で集計 
- フロント側で時間軸を揃えるのがつらすぎる
realtime反映は別PRで。
=> Create score chart

scripts/leaderboard/prisma/migrations/20220411095028_/migration.sql, scripts/leaderboard/prisma/schema.prisma, scripts/measure/package.json, scripts/measure/src/database.ts, scripts/measure/src/index.ts, scripts/measure/src/vrt.ts, yarn.lock
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/issues/25
=> Add upload checking VRT image file

scripts/leaderboard/prisma/migrations/20220412003953_/migration.sql, scripts/leaderboard/prisma/schema.prisma, scripts/leaderboard/prisma/seed.ts
=> Modify vrt url to required

.github/workflows/deploy.yml
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/issues/46 同実行数とメモリのサーバ調整
=> Modify setting concurrency of measure server

scripts/leaderboard/app/components/forms/JoinTeam.tsx, scripts/leaderboard/app/components/forms/MeasureRequest.tsx, scripts/leaderboard/app/request/Queue.ts, scripts/leaderboard/app/routes/dashboard/__layout/index.tsx, scripts/leaderboard/app/routes/dashboard/__layout/teams.tsx
実行待ち/実行中のキューがあるときは新規に計測リクエストできないようにする
=> Update validation; disable queue registration when having running one

.github/workflows/deploy.yml, scripts/measure/src/vrt.ts
VRT結果の画像の圧縮処理を待たずにアップロードしようとしてエラーとなることの修正
=> Fix create vrt image archive

.github/workflows/deploy.yml
=> Fix set environments to Cloud Run

scripts/leaderboard/app/request/Measurement.ts
=> Fix score graph timezone

.github/workflows/deploy.yml
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/issues/78
週明けの本番変更時にマージする予定
=> Modify cache for container build

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
- cloudflareのsecret生成時の環境の指定を忘れていた
- cloud run へのdeployのための認証が漏れていた
=> Fix github actions for deploy

scripts/leaderboard/app/zod/measurement.ts, scripts/leaderboard/prisma/migrations/20220415065002_/migration.sql, scripts/leaderboard/prisma/schema.prisma, scripts/leaderboard/prisma/seed.ts, scripts/measure/src/database.ts, scripts/measure/src/index.ts, scripts/measure/src/vrt.ts
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/issues/74
これをマージしてしまうと現状の本番データが消えてしまうため対策するまでマージしない。
=> Modify scoring when vrt failed

scripts/scoring/src/index.ts
=> Modify scoring page url

scripts/leaderboard/app/components/QueueList.tsx, scripts/leaderboard/app/request/Queue.ts, scripts/leaderboard/app/zod/measurement.ts, scripts/leaderboard/app/zod/queue.ts, scripts/leaderboard/prisma/migrations/20220420025559_/migration.sql, scripts/leaderboard/prisma/schema.prisma, scripts/leaderboard/prisma/seed.ts, scripts/measure/src/database.ts, scripts/measure/src/measure.ts
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/issues/71
~~動作テストは何もしてない。~~
=> Add download link of VRT

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
=> Modify server spec for measure

scripts/leaderboard/app/routes/dashboard/__layout/index.tsx
=> Update dashboard layout

scripts/measure/src/index.ts
=> modify display log when error

scripts/vrt/src/capture_screenshot.ts
=> Modify wait event for VRT

scripts/vrt/src/capture_screenshot.ts
=> Add debug message on captureScreenshot

scripts/leaderboard/app/components/Chart.tsx, scripts/leaderboard/app/components/MeasurementReuest.tsx, scripts/leaderboard/app/components/QueueList.tsx, scripts/leaderboard/app/request/Queue.ts, scripts/leaderboard/app/routes/dashboard/__layout/index.tsx, scripts/leaderboard/package.json, yarn.lock
=> Update QueueList for display message and score

scripts/measure/src/index.ts
https://github.com/ateam-dev/web-speed-hackathon-2021-leaderboard/issues/104
=> Fix update fail status when vrt is 404

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml, scripts/leaderboard/app/components/QueueList.tsx, scripts/measure/package.json, scripts/measure/src/database.ts, scripts/measure/src/index.ts, scripts/measure/src/measure.ts, yarn.lock
まだ、実際にはうごかしていないので、一旦ステージングに出してみて動くかどうかを見たい。
=> Manage dead queues

scripts/leaderboard/app/request/Measurement.ts, scripts/leaderboard/app/request/Teaming.ts, scripts/leaderboard/app/routes/dashboard/__layout/index.tsx
| 時間前 | 時間後 |
| --- | --- |
|![スクリーンショット 2022-04-28 午後2 13 15](https://user-images.githubusercontent.com/6711766/165681184-f4e3cc87-a2db-46aa-af3e-14169bc48519.png)|![スクリーンショット 2022-04-28 午後2 13 28](https://user-images.githubusercontent.com/6711766/165681189-ada1ccce-1c51-4273-bb6c-8129bed44245.png)|
=> Hide scores and rankings when the time comes

scripts/leaderboard/app/libs/backdoor.server.ts, scripts/leaderboard/app/routes/dashboard/__layout/backdoor.ts, scripts/leaderboard/app/routes/dashboard/__layout/index.tsx
|cookieにbackdoorのデータを持っていないとき|cookieにbackdoorのデータを持っているとき|
|---|---|
|![スクリーンショット 2022-04-28 午後2 36 30](https://user-images.githubusercontent.com/6711766/165683776-82f2b7ca-34e3-42bb-a3cd-f64a9ebf88aa.png)|![スクリーンショット 2022-04-28 午後2 36 49](https://user-images.githubusercontent.com/6711766/165683812-be99fe5d-1a5c-477b-8743-28d3d5b8419f.png)|
=> Active backdoor
